version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - .:/app
    ports:
      - 8080:8080
    env_file:
      - dev.env
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - dev.env
  pytest:
    build: .
    command: pytest
    volumes:
      - .:/app
    env_file:
      - dev.env
    depends_on:
      - db

volumes:
  postgres_data: